/**
 * TheAuth on Cloudflare Workers with D1
 *
 * Setup:
 *   wrangler d1 create theauth-db          # paste the database_id into wrangler.toml
 *   pnpm migrations:apply                  # creates the tables from migrations/0001_initial.sql
 *   wrangler secret put SESSION_SECRET
 *   wrangler deploy
 *
 * The D1 binding is declared in wrangler.toml:
 *
 *   [[d1_databases]]
 *   binding = "DB"
 *   database_name = "theauth-db"
 *   database_id = "<your-database-id>"
 *
 * The tables come from migrations/0001_initial.sql, which is generated by
 * `pnpm migrations:generate` (it calls getMigrationStatements from
 * @glinr/theauth). The worker passes `skipMigrations: true` so a request never
 * pays for a schema check. If you prefer not to manage a migration file, drop
 * `skipMigrations` and createTheAuth will run CREATE TABLE IF NOT EXISTS once
 * per isolate start instead.
 */

import { createTheAuth } from "@glinr/theauth";
import { theAuthHono } from "@glinr/theauth-hono";
import { Hono } from "hono";

// Cloudflare Workers env bindings
type Env = {
	DB: D1Database;
	SESSION_SECRET: string;
};

const app = new Hono<{ Bindings: Env }>();

// Health check, no DB required
app.get("/health", (c) => c.json({ status: "ok" }));

type Auth = Awaited<ReturnType<typeof createTheAuth>>;

// One TheAuth instance per isolate. The D1 binding and secret do not change
// for the life of an isolate, so building it once avoids repeating setup on
// every request.
let authPromise: Promise<Auth> | undefined;

function getAuth(env: Env): Promise<Auth> {
	authPromise ??= createTheAuth({
		database: {
			provider: "d1",
			binding: env.DB,
			// Tables come from migrations/0001_initial.sql (wrangler d1 migrations apply).
			skipMigrations: true,
		},
		auth: {
			session: {
				secret: env.SESSION_SECRET,
			},
		},
		agents: {
			enabled: true,
			maxPerUser: 100,
			defaultPermissions: [],
			auditAll: true,
			tokenExpiry: "24h",
		},
	});
	return authPromise;
}

// All TheAuth routes under /api
app.all("/api/*", async (c) => {
	const auth = await getAuth(c.env);

	// Mount theAuthHono under the /api prefix by stripping it before dispatch
	// Demo only: no authentication on the management routes. Real apps pass
	// `authenticate` (see the adapter docs).
	const api = theAuthHono(auth, { allowUnauthenticated: true });
	const url = new URL(c.req.url);
	const stripped = new Request(new URL(url.pathname.replace(/^\/api/, "") || "/", url), c.req.raw);
	return api.fetch(stripped, c.env, c.executionCtx);
});

export default app;
